Devenir Bibliothécaire
	Description : Un membre demande à devenir bibliothécaire.
	Acteurs : Membre, Bibliothécaire
	Prérequis : Il existe au moins un Bibliothécaire actif.
	Étapes :
1.	Un membre demande à l’application à devenir bibliothécaires.
2.	L’application enregistre la demande et soumet la demande aux bibliothécaires.
3.	L’application sur le média d’un autre bibliothécaire transmet à son 
utilisateur la demande pour modération.
4.	L’application demande au bibliothécaire s’il :
•	accepte,
•	rejette,
•	n’a pas d’avis,
•	ou souhaite ignorer la candidature.
5.	Le bibliothécaire indique à l’application quel est son choix.
6.	L’application partage de façon anonyme et unique ce choix avec les autres
 applications sur les médias des autres Bibliothécaires.
7.	Le Bibliothécaire peut modifier son choix tant que le délai imparti n’est
 pas écoulé.
8.	Une fois le délai écoulé, les applications des bibliothécaires propagent aux
 autres applications la décision automatique prise ainsi :
•	Si la majorité des bibliothécaires ont accepté la candidature du membre alors
 celui-ci devient bibliothécaire.
9.	Le membre consulte la décision depuis l’application sur son média.
10.	Si l’application du futur bibliothécaire constate qu’il est promu bibliothécaire 
alors il reçoit les droits lui permettant d’accéder à l’ensemble des contenus et de pouvoir accepter ou refuser les modérations.
11.	Sinon l’application indique le refus de sa promotion.
	Scénarios alternatifs :
La majorité des bibliothécaires refuse la promotion.

	Scénarios erreurs :
	Données, documents, écrans :

@startuml
actor Membre 
actor Bibliothécaire
participant Application as App 
participant UIManager as UIM 
   
Membre -> App : Proposition Candidature Bibliothécaire 
App -> UIM : NewApplication()
UIM -> Bibliothécaire : Affiche Candidature  (accepte,rejette,n’a pas d’avis, ignorer)
Bibliothécaire --> App : Reponse candidature 
App -> UIM : Result()
UIM -> Bibliothécaires : affiche les resultat de facon anonyme
Alt Modification choix Delai imparti
Bibliothécaire -> App : Modification choix 
App -> UIM : Result()
UIM -> Bibliothécaires : affiche les resultat de facon anonyme
Else  Temps écoulé 
UIM -> App : Vote effectué 
Alt Acceptation Candidature 
App -> Membre:  Promotion et Activation Droits 
else Refus Candidature 
App -> Membre : Message refus de promotion
End 
End   


@enduml
